version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    quarkus:
      patterns:
        - "quarkus.*"
    dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "quarkus.*"
