version: "3.9"
services:
  code-quarkus-api:
    image: quay.io/quarkus/code-quarkus-api
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.env.redhat
  code-quarkus-frontend:
    image: quay.io/redhat-developer/code-quarkus
    ports:
      - "3000:8082"
    depends_on:
      - code-quarkus-api