name: Frontend Tests
on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
    paths:
      - 'frontend/**'

env:
  # Workaround testsuite locale issue
  LANG: en_US.UTF-8

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: n1hility/cancel-previous-runs@953c92201f368370112ea2754545cb4468d89f12 #v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Yarn Packages
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: /.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend/yarn.lock', 'lib/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install frontend
        working-directory: frontend
        run: yarn install --frozen-lockfile
      - name: Build frontend
        working-directory: frontend
        run: |
          REACT_APP_BACKEND_URL=https://code.quarkus.stage.redhat.com yarn build
          echo ${{ github.event.number }} > ./build/pr-id.txt
      - name: Publishing build directory for PR preview
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: ./frontend/build
          retention-days: 3
